name: CI tests macOS

on:
  push:
    branches:
      - master
    paths:
      - 'test/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'test/*'
      - '.github/workflows/ci-macos.yml'

jobs:
  macos-tests:
    timeout-minutes: 10
    runs-on: macos-latest
    name: "macOS tests"
    steps:
    - uses: actions/checkout@v5

    - name: Build and configure
      run: |
        cd test
        cmake .
        make

    - name: libkqueue test suite
      env:
        KQUEUE_DEBUG: yes
      run: |
        ./test/libkqueue-test -n 5
