name: CI tests macOS

on:
  push:
    branches:
      - master
    paths:
      - 'test/*'
      - 'tools/test-stack-dump.sh'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'test/*'
      - 'tools/test-stack-dump.sh'
      - '.github/workflows/ci-macos.yml'
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  macos-tests:
    timeout-minutes: ${{ github.event_name == 'schedule' && 60 || 10 }}
    runs-on: macos-latest
    name: "macOS tests"
    steps:
    - uses: actions/checkout@v5

    - name: Build and configure
      run: |
        cd test
        cmake .
        make

    - name: libkqueue test suite
      env:
        KQUEUE_DEBUG: yes
      run: |
        ./test/libkqueue-test \
          --watchdog-timeout=120 \
          --watchdog-cmd="${{ github.workspace }}/tools/test-stack-dump.sh" \
          -n ${{ github.event_name == 'schedule' && 50 || 1 }}
