name: CI Windows

on:
  push:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'include/sys/*'
      - 'src/common/*'
      - 'src/windows/*'
      - 'test/*'
      - '.github/workflows/ci-windows.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'src/common/*'
      - 'src/windows/*'
      - 'test/*'
      - '.github/workflows/ci-windows.yml'

env:
  KQUEUE_DEBUG: yes

jobs:
  windows-build:
    timeout-minutes: 5
    runs-on: windows-2019
    name: CI-windows (build)

    steps:
      - uses: actions/checkout@v2

      - name: Configure build system
        run: |
          cmake --version
          cmake -S . -B build_x64 -A x64 -G "Visual Studio 16 2019" -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build libkqueue
        run: |
          cmake --build build_x64 --target install --config Release --parallel 1

